version: '3'
services:
  bigstream:
    image: "bigstream:${BIGSTREAM_TAG}"
    build: ./
    container_name: bs_bigstream
    restart: always
    networks:
     - bsnet
    ports:
     - "19980:19980"
     - "19080:19080"
     - "19180:19180"
     - "19150:19150/udp"
    environment:
     - "BS_SECRET=${BS_SECRET}"
    volumes:
     - ${VOLUME}/bigstream/data:/var/bigstream/data
  redis:
    image: "redis:${REDIS_TAG}"
    command: redis-server --appendonly yes
    container_name: bs_redis_server
    restart: always
    networks:
       bsnet:
          aliases:
             - redis-server
    ports:
     - "6379:6379"
    volumes:
     - ${VOLUME}/redis/data:/data
  rabbitmq:
    image: "igridproject/rabbitmq"
    command: rabbitmq-server --hostname rabbitmq-server
    container_name: bs_rabbitmq_server
    restart: always
    networks:
       bsnet:
          aliases:
             - rabbitmq-server
    ports:
     - "5672:5672"
networks:
  bsnet:
     driver: bridge